spring:
  application:
    name: core-banking-service
  datasource:
    url: jdbc:mysql://localhost:3306/banking_core_service
    username: root
    password: itaChi*123456789
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/

info:
  app:
    name: ${spring.application.name}